#!/usr/bin/expect -f
set fields [open "users" r]
set user [gets $fields]
while {[string length $user] > 0} {
 
   set timeout 3
   spawn ipa user-mod $user --password
   expect "Пароль: \r"
   send -- "Qwerty12\r"
   expect "Повторно введите Пароль для проверки: \r"
   send -- "Qwerty12\r"
   expect eof
 
 
   set timeout 3
   spawn su $user
   expect "Пароль: \r"
   send -- "Qwerty12\r"
   expect "Срок действия пароля истёк. Необходимо сейчас изменить ваш пароль.\r"
   expect "Текущий пароль: \r"
   send -- "Qwerty12\r"
   expect "Новый пароль : \r"
   send -- "Qwerty12\r"
   expect "Повторите ввод нового пароля : \r"
   send -- "Qwerty12\r"
   send -- "exit"
   expect eof
 
  set user [gets $fields]
}
close $fields
